enum constants {
  SELECT_BOOK = 'SELECT_BOOK',
  GET_BOOK_ACTION = 'GET_BOOK_ACTION',
  ASYNC_GET_BOOK_ACTION = 'ASYNC_GET_BOOK_ACTION',
  TOGGLE_REFRESH_ACTION = 'TOGGLE_REFRESH_ACTION',
  ASYNC_GET_BOOK_ACTION_REFRESH = 'ASYNC_GET_BOOK_ACTION_REFRESH',
  GET_BOOK_ACTION_NEXT_PAGE = 'GET_BOOK_ACTION_NEXT_PAGE',
  ASYNC_GET_BOOK_ACTION_NEXT_PAGE = 'ASYNC_GET_BOOK_ACTION_NEXT_PAGE',
  SEARCH_BOOK_ACTION = 'SEARCH_BOOK_ACTION',
  ASYNC_SEARCH_BOOK_ACTION = 'ASYNC_SEARCH_BOOK_ACTION',
}

export default constants;
